import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { listInterviews } from "../services/api";

function ScheduledInterviews() {
  const navigate = useNavigate();
  const [scheduled, setScheduled] = useState([]);
  const [error, setError] = useState("");

  useEffect(() => {
    listInterviews()
      .then((response) => {
        const upcoming = response.interviews.filter((item) => !item.completed);
        setScheduled(upcoming);
      })
      .catch((err) => setError(err.message || "Unable to load interview history."));
  }, []);

  const handleStartSession = (session) => {
    navigate("/interview", { state: { interviewId: session.id } });
  };

  return (
    <div className="scheduled-modern">
      <div className="scheduled-header-modern">
        <h1>Scheduled Sessions</h1>
        <p>Continue any in-progress interview generated by the local backend.</p>
      </div>

      <div className="scheduled-list-modern">
        <h3>Active Sessions</h3>

        {scheduled.map((session) => (
          <div key={session.id} className="scheduled-item-modern">
            <div>
              <strong>
                {session.type} · {session.difficulty}
              </strong>
              <div className="session-meta-modern">
                {new Date(session.created_at).toLocaleString()} · {session.status}
              </div>
            </div>

            <button className="btn-secondary-modern" onClick={() => handleStartSession(session)}>
              Continue
            </button>
          </div>
        ))}

        {!scheduled.length && <p className="hint-modern">No active interviews yet. Start one from Home.</p>}
        {error && <div className="error-text">{error}</div>}
      </div>
    </div>
  );
}

export default ScheduledInterviews;
